"""addendum: lessons, items, todos and flexible links

Revision ID: 17da8cdf5990
Revises: b1c2d3e4f5a6
Create Date: 2026-08-22 18:14:52.017358
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = '17da8cdf5990'
down_revision = 'b1c2d3e4f5a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    #
    # Autogenerate wanted to DROP the FTS5 virtual tables and their shadow
    # tables, because they exist in the database but not in SQLModel's
    # metadata. Those drops were removed by hand, and migrations/env.py now
    # filters FTS tables out of autogenerate so this cannot recur.
    op.create_table('todos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.create_index('ix_todos_due_date', ['due_date'], unique=False)

    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('subtopic_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subtopic_id'], ['subtopics.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lessons_subtopic_id'), ['subtopic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lessons_topic_id'), ['topic_id'], unique=False)
        batch_op.create_index('ix_lessons_topic_position', ['topic_id', 'position'], unique=False)

    op.create_table('lesson_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lesson_items', schema=None) as batch_op:
        batch_op.create_index('ix_lesson_items_lesson_position', ['lesson_id', 'position'], unique=False)

    op.create_table('lesson_resource_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_id', 'resource_id', name='uq_lesson_resource')
    )
    with op.batch_alter_table('lesson_resource_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lesson_resource_links_lesson_id'), ['lesson_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_resource_links_resource_id'), ['resource_id'], unique=False)

    op.create_table('note_lesson_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('note_id', 'lesson_id', name='uq_note_lesson')
    )
    with op.batch_alter_table('note_lesson_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_note_lesson_links_lesson_id'), ['lesson_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_note_lesson_links_note_id'), ['note_id'], unique=False)

    op.create_table('note_resource_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('note_id', 'resource_id', name='uq_note_resource')
    )
    with op.batch_alter_table('note_resource_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_note_resource_links_note_id'), ['note_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_note_resource_links_resource_id'), ['resource_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note_resource_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_note_resource_links_resource_id'))
        batch_op.drop_index(batch_op.f('ix_note_resource_links_note_id'))

    op.drop_table('note_resource_links')
    with op.batch_alter_table('note_lesson_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_note_lesson_links_note_id'))
        batch_op.drop_index(batch_op.f('ix_note_lesson_links_lesson_id'))

    op.drop_table('note_lesson_links')
    with op.batch_alter_table('lesson_resource_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lesson_resource_links_resource_id'))
        batch_op.drop_index(batch_op.f('ix_lesson_resource_links_lesson_id'))

    op.drop_table('lesson_resource_links')
    with op.batch_alter_table('lesson_items', schema=None) as batch_op:
        batch_op.drop_index('ix_lesson_items_lesson_position')

    op.drop_table('lesson_items')
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_index('ix_lessons_topic_position')
        batch_op.drop_index(batch_op.f('ix_lessons_topic_id'))
        batch_op.drop_index(batch_op.f('ix_lessons_subtopic_id'))

    op.drop_table('lessons')
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.drop_index('ix_todos_due_date')

    op.drop_table('todos')
    # ### end Alembic commands ###
