"""initial schema from spec section 6

Revision ID: 6a9a48c36ece
Revises: 
Create Date: 2026-08-22 15:05:14.596784
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = '6a9a48c36ece'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('vector', sa.LargeBinary(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dim', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('embeddings', schema=None) as batch_op:
        batch_op.create_index('ix_embeddings_target', ['target_type', 'target_id'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope_json', sa.Text(), nullable=True),
    sa.Column('planned_count', sa.Integer(), nullable=False),
    sa.Column('completed_count', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value_json', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('colour', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subjects_name'), ['name'], unique=False)

    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('colour', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_name'), ['name'], unique=False)

    op.create_table('pipeline_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('block_count', sa.Integer(), nullable=False),
    sa.Column('concepts_created', sa.Integer(), nullable=False),
    sa.Column('concepts_updated', sa.Integer(), nullable=False),
    sa.Column('concepts_merged', sa.Integer(), nullable=False),
    sa.Column('edges_proposed', sa.Integer(), nullable=False),
    sa.Column('mcqs_generated', sa.Integer(), nullable=False),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('taggings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('taggings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_taggings_tag_id'), ['tag_id'], unique=False)

    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topics_subject_id'), ['subject_id'], unique=False)

    op.create_table('subtopics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subtopics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subtopics_topic_id'), ['topic_id'], unique=False)

    op.create_table('concepts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('normalised_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('subtopic_id', sa.Integer(), nullable=True),
    sa.Column('importance', sa.Float(), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('coverage_profile_json', sa.Text(), nullable=True),
    sa.Column('created_by_job_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_job_id'], ['pipeline_jobs.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['subtopic_id'], ['subtopics.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('concepts', schema=None) as batch_op:
        batch_op.create_index('ix_concepts_normalised_name', ['normalised_name'], unique=False)

    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('resource_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('subtopic_id', sa.Integer(), nullable=True),
    sa.Column('progress_pct', sa.Integer(), nullable=False),
    sa.Column('progress_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_opened_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['subtopic_id'], ['subtopics.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concept_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('alias', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('normalised_alias', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('concept_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_concept_aliases_concept_id'), ['concept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_concept_aliases_normalised_alias'), ['normalised_alias'], unique=False)

    op.create_table('concept_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_concept_id', sa.Integer(), nullable=False),
    sa.Column('target_concept_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['pipeline_jobs.id'], ),
    sa.ForeignKeyConstraint(['source_concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['target_concept_id'], ['concepts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('concept_edges', schema=None) as batch_op:
        batch_op.create_index('ix_concept_edges_source', ['source_concept_id'], unique=False)
        batch_op.create_index('ix_concept_edges_target', ['target_concept_id'], unique=False)

    op.create_table('concept_merges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merged_from_id', sa.Integer(), nullable=False),
    sa.Column('merged_into_id', sa.Integer(), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=True),
    sa.Column('decided_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reverted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['pipeline_jobs.id'], ),
    sa.ForeignKeyConstraint(['merged_from_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['merged_into_id'], ['concepts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('task', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('thinking_level', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('request_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cached_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.Column('concept_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['pipeline_jobs.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_runs', schema=None) as batch_op:
        batch_op.create_index('ix_llm_runs_concept_id', ['concept_id'], unique=False)
        batch_op.create_index('ix_llm_runs_created_at', ['created_at'], unique=False)

    op.create_table('mcqs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('dimension', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stem', sa.Text(), nullable=False),
    sa.Column('options_json', sa.Text(), nullable=False),
    sa.Column('correct_option_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('distractor_rationale_json', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('times_served', sa.Integer(), nullable=False),
    sa.Column('times_correct', sa.Integer(), nullable=False),
    sa.Column('consecutive_correct', sa.Integer(), nullable=False),
    sa.Column('last_served_at', sa.DateTime(), nullable=True),
    sa.Column('prompt_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('retired_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['pipeline_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mcqs', schema=None) as batch_op:
        batch_op.create_index('ix_mcqs_concept_status', ['concept_id', 'status'], unique=False)

    op.create_table('misconceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('times_seen', sa.Integer(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('misconceptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_misconceptions_concept_id'), ['concept_id'], unique=False)

    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('study_date', sa.Date(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('subtopic_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['subtopic_id'], ['subtopics.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index('ix_notes_study_date', ['study_date'], unique=False)

    op.create_table('review_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('dimension', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fsrs_stability', sa.Float(), nullable=True),
    sa.Column('fsrs_difficulty', sa.Float(), nullable=True),
    sa.Column('fsrs_state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fsrs_step', sa.Integer(), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('lapses', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('suspended', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('concept_id', 'dimension', name='uq_review_items_concept_dim')
    )
    with op.batch_alter_table('review_items', schema=None) as batch_op:
        batch_op.create_index('ix_review_items_due_at', ['due_at'], unique=False)

    op.create_table('mcq_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mcq_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('selected_option_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('response_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['mcq_id'], ['mcqs.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mcq_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mcq_attempts_mcq_id'), ['mcq_id'], unique=False)

    op.create_table('note_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('block_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('processed_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('note_blocks', schema=None) as batch_op:
        batch_op.create_index('ix_note_blocks_note_position', ['note_id', 'position'], unique=False)

    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('review_item_id', sa.Integer(), nullable=True),
    sa.Column('dimension', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('expected_answer', sa.Text(), nullable=True),
    sa.Column('key_points_json', sa.Text(), nullable=True),
    sa.Column('common_misconceptions_json', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.Column('source_note_ids_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('generation_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prompt_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('embedding_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['embedding_id'], ['embeddings.id'], ),
    sa.ForeignKeyConstraint(['review_item_id'], ['review_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_concept_id'), ['concept_id'], unique=False)

    op.create_table('concept_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('note_block_id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('invalidated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['pipeline_jobs.id'], ),
    sa.ForeignKeyConstraint(['note_block_id'], ['note_blocks.id'], ),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('concept_sources', schema=None) as batch_op:
        batch_op.create_index('ix_concept_sources_concept_id', ['concept_id'], unique=False)

    op.create_table('pipeline_job_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('note_block_id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('text_snapshot', sa.Text(), nullable=False),
    sa.Column('hash_snapshot', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['pipeline_jobs.id'], ),
    sa.ForeignKeyConstraint(['note_block_id'], ['note_blocks.id'], ),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pipeline_job_blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pipeline_job_blocks_job_id'), ['job_id'], unique=False)

    op.create_table('question_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('review_item_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('user_answer', sa.Text(), nullable=True),
    sa.Column('is_retest', sa.Boolean(), nullable=False),
    sa.Column('retest_of_attempt_id', sa.Integer(), nullable=True),
    sa.Column('evaluator_json', sa.Text(), nullable=True),
    sa.Column('evaluator_rating', sa.Integer(), nullable=True),
    sa.Column('user_override_rating', sa.Integer(), nullable=True),
    sa.Column('final_rating', sa.Integer(), nullable=True),
    sa.Column('response_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['retest_of_attempt_id'], ['question_attempts.id'], ),
    sa.ForeignKeyConstraint(['review_item_id'], ['review_items.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_attempts_question_id'), ['question_id'], unique=False)

    op.create_table('session_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('item_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mcq_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('review_item_id', sa.Integer(), nullable=True),
    sa.Column('selection_bucket', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('served_at', sa.DateTime(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mcq_id'], ['mcqs.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['review_item_id'], ['review_items.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_items_session_id'), ['session_id'], unique=False)

    op.create_table('review_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_item_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('dimension', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('question_attempt_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('evaluator_rating', sa.Integer(), nullable=True),
    sa.Column('user_override_rating', sa.Integer(), nullable=True),
    sa.Column('evaluator_json', sa.Text(), nullable=True),
    sa.Column('response_ms', sa.Integer(), nullable=True),
    sa.Column('due_before', sa.DateTime(), nullable=True),
    sa.Column('due_after', sa.DateTime(), nullable=True),
    sa.Column('stability_before', sa.Float(), nullable=True),
    sa.Column('stability_after', sa.Float(), nullable=True),
    sa.Column('difficulty_before', sa.Float(), nullable=True),
    sa.Column('difficulty_after', sa.Float(), nullable=True),
    sa.Column('is_retest', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['question_attempt_id'], ['question_attempts.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['review_item_id'], ['review_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_logs', schema=None) as batch_op:
        batch_op.create_index('ix_review_logs_item_created', ['review_item_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_review_logs_item_created')

    op.drop_table('review_logs')
    with op.batch_alter_table('session_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_items_session_id'))

    op.drop_table('session_items')
    with op.batch_alter_table('question_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_attempts_question_id'))

    op.drop_table('question_attempts')
    with op.batch_alter_table('pipeline_job_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipeline_job_blocks_job_id'))

    op.drop_table('pipeline_job_blocks')
    with op.batch_alter_table('concept_sources', schema=None) as batch_op:
        batch_op.drop_index('ix_concept_sources_concept_id')

    op.drop_table('concept_sources')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_concept_id'))

    op.drop_table('questions')
    with op.batch_alter_table('note_blocks', schema=None) as batch_op:
        batch_op.drop_index('ix_note_blocks_note_position')

    op.drop_table('note_blocks')
    with op.batch_alter_table('mcq_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mcq_attempts_mcq_id'))

    op.drop_table('mcq_attempts')
    with op.batch_alter_table('review_items', schema=None) as batch_op:
        batch_op.drop_index('ix_review_items_due_at')

    op.drop_table('review_items')
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index('ix_notes_study_date')

    op.drop_table('notes')
    with op.batch_alter_table('misconceptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_misconceptions_concept_id'))

    op.drop_table('misconceptions')
    with op.batch_alter_table('mcqs', schema=None) as batch_op:
        batch_op.drop_index('ix_mcqs_concept_status')

    op.drop_table('mcqs')
    with op.batch_alter_table('llm_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_llm_runs_created_at')
        batch_op.drop_index('ix_llm_runs_concept_id')

    op.drop_table('llm_runs')
    op.drop_table('concept_merges')
    with op.batch_alter_table('concept_edges', schema=None) as batch_op:
        batch_op.drop_index('ix_concept_edges_target')
        batch_op.drop_index('ix_concept_edges_source')

    op.drop_table('concept_edges')
    with op.batch_alter_table('concept_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_concept_aliases_normalised_alias'))
        batch_op.drop_index(batch_op.f('ix_concept_aliases_concept_id'))

    op.drop_table('concept_aliases')
    op.drop_table('resources')
    with op.batch_alter_table('concepts', schema=None) as batch_op:
        batch_op.drop_index('ix_concepts_normalised_name')

    op.drop_table('concepts')
    with op.batch_alter_table('subtopics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subtopics_topic_id'))

    op.drop_table('subtopics')
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topics_subject_id'))

    op.drop_table('topics')
    with op.batch_alter_table('taggings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_taggings_tag_id'))

    op.drop_table('taggings')
    op.drop_table('pipeline_jobs')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_name'))

    op.drop_table('tags')
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subjects_name'))

    op.drop_table('subjects')
    op.drop_table('settings')
    op.drop_table('sessions')
    with op.batch_alter_table('embeddings', schema=None) as batch_op:
        batch_op.drop_index('ix_embeddings_target')

    op.drop_table('embeddings')
    # ### end Alembic commands ###
