"""hold blocks back from processing

Revision ID: 6d767d1241a5
Revises: ab57bf73b749
Create Date: 2026-08-23 23:19:25.569677
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = '6d767d1241a5'
down_revision = 'ab57bf73b749'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # A block the user has parked: written down, not studied yet, and not to
    # be sent to the model until they say so.
    with op.batch_alter_table('note_blocks', schema=None) as batch_op:
        # server_default: the table has rows, and a NOT NULL column with no
        # default fails the moment one exists. Everything written so far was
        # meant to be processed, so it defaults to false.
        batch_op.add_column(sa.Column('skip_processing', sa.Boolean(),
                                      nullable=False, server_default=sa.text('0')))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note_blocks', schema=None) as batch_op:
        batch_op.drop_column('skip_processing')

    # ### end Alembic commands ###
