"""note block code language

Revision ID: 73e9df3a2e9d
Revises: 06e630770a79
Create Date: 2026-08-22 23:47:44.322933
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = '73e9df3a2e9d'
down_revision = '06e630770a79'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Nullable, so every existing block is untouched: a block with no language
    # is not a code block, or is one whose language nobody chose.
    with op.batch_alter_table('note_blocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note_blocks', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
