"""page links and the revisit status

Revision ID: 94766c42ca16
Revises: eac45ca21273
Create Date: 2026-08-23 02:27:03.694683
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = '94766c42ca16'
down_revision = 'eac45ca21273'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    with op.batch_alter_table('subtopics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_column('url')

    with op.batch_alter_table('subtopics', schema=None) as batch_op:
        batch_op.drop_column('url')

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_column('url')

    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_column('url')

    # ### end Alembic commands ###
