"""job failure reason

Revision ID: eac45ca21273
Revises: 73e9df3a2e9d
Create Date: 2026-08-23 02:19:55.005688
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = 'eac45ca21273'
down_revision = '73e9df3a2e9d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Nullable: every existing job predates the distinction, and "no idea" is
    # an honest value for them.
    with op.batch_alter_table('pipeline_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('error_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('error_action', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pipeline_jobs', schema=None) as batch_op:
        batch_op.drop_column('error_action')
        batch_op.drop_column('error_reason')

    # ### end Alembic commands ###
