"""resource groups

Revision ID: feb536c4ee1b
Revises: 94766c42ca16
Create Date: 2026-08-23 13:55:27.311270
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = 'feb536c4ee1b'
down_revision = '94766c42ca16'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # A heading in the resource library. Nullable on resources: everything
    # already saved stays where it is, ungrouped, until it is filed.
    op.create_table('resource_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('colour', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resource_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resource_groups_name'), ['name'], unique=False)

    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_resources_group_id'), ['group_id'], unique=False)
        # Named: SQLite's batch ALTER rebuilds the table and cannot add an
        # anonymous constraint.
        batch_op.create_foreign_key(
            'fk_resources_group_id', 'resource_groups', ['group_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_constraint('fk_resources_group_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_resources_group_id'))
        batch_op.drop_column('group_id')

    with op.batch_alter_table('resource_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resource_groups_name'))

    op.drop_table('resource_groups')
    # ### end Alembic commands ###
